# Reason build pipeline

name: $(Build.SourceVersion)
jobs:
- job: Linux_esy
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i/
    ESY__CACHE_SOURCE_TARBALL_PATH: /home/vsts/.esy/source-tarballs

  steps:
  # TODO: Uncomment this when you have a green build, to enable caching
  # - template: restore-build-cache.yml
  - template: esy-build-steps.yml
  # - template: publish-build-cache.yml

- job: Mac_opam_4071
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS 10.13'

  variables:
    OCAML_VERSION: 4.07.1

  steps:
  - template: opam-build-steps.yml

- job: Mac_opam_4061
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS 10.13'

  variables:
    OCAML_VERSION: 4.06.1

  steps:
  - template: opam-build-steps.yml

- job: Mac_opam_4023
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS 10.13'

  variables:
    OCAML_VERSION: 4.02.3

  steps:
  - template: opam-build-steps.yml

- job: MacOS_esy
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS 10.13'

  variables:
    ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i/
    ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source-tarballs

  steps:
  # TODO: Uncomment this when you have a green build, to enable caching
  # - template: restore-build-cache.yml
  - template: esy-build-steps.yml
  # - template: publish-build-cache.yml

- job: Windows_esy
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'

  variables:
    ESY__CACHE_INSTALL_PATH: C:\Users\VssAdministrator\.esy\3_\i
    ESY__CACHE_SOURCE_TARBALL_PATH: C:\Users\VssAdministrator\.esy\source-tarballs

  steps:
  - template: restore-build-cache.yml
  - template: esy-build-steps.yml
  - template: publish-build-cache.yml
